# fly.toml app configuration file generated for notes-lingering-dream-1309 on 2025-04-23T15:33:39-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'notes-lingering-dream-1309'
primary_region = 'mia'

[env]
  PORT = "3001"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
